//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aug2015Backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public Vacation()
        {
            this.AgeRange = new HashSet<AgeRange>();
            this.Comment = new HashSet<Comment>();
            this.When = new HashSet<Period>();
            this.Who = new HashSet<Group>();
            this.Included = new HashSet<IncludedItem>();
            this.Picture = new HashSet<Picture>();
        }
    
        public int Id { get; set; }
        public string Titel { get; set; }
        public int NumberOfParticipants { get; set; }
        public string PromoText { get; set; }
    
        public virtual ICollection<AgeRange> AgeRange { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ContactInformation ContactInformation { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Period> When { get; set; }
        public virtual ICollection<Group> Who { get; set; }
        public virtual Picture Cover { get; set; }
        public virtual Price Cost { get; set; }
        public virtual ICollection<IncludedItem> Included { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
    }
}
