//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aug2015Backend.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public Vacation()
        {
            this.AgeRange = new HashSet<AgeRange>();
        }
    
        public int Id { get; set; }
        public string Titel { get; set; }

        [JsonProperty(PropertyName = "Leeftijd")]
        public virtual ICollection<AgeRange> AgeRange { get; set; }
    }
}
